name: Testproject
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Print greeting
        run: | 
            echo "Heeloo world"
            echo "try success"