name: Testproject
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Heeloo world"
          echo "try success"
      - name: Create a dummy log file
        run: |
            mkdir -p logs
            echo "This is a sample log file." > logs/app.log
      - name: Get build artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: logs
          path: logs/app.log
